var user =
{
  "login": "rogersgt",
  "id": 14983357,
  "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/rogersgt",
  "html_url": "https://github.com/rogersgt",
  "followers_url": "https://api.github.com/users/rogersgt/followers",
  "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
  "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
  "organizations_url": "https://api.github.com/users/rogersgt/orgs",
  "repos_url": "https://api.github.com/users/rogersgt/repos",
  "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
  "received_events_url": "https://api.github.com/users/rogersgt/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Grady Rogers",
  "company": null,
  "blog": null,
  "location": null,
  "email": "rogersgt819@gmail.com",
  "hireable": null,
  "bio": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2015-10-05T17:54:21Z",
  "updated_at": "2015-10-07T16:06:34Z"
};

var repos =
[
  {
    "id": 44262904,
    "name": "adventure_game",
    "full_name": "rogersgt/adventure_game",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/adventure_game",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/adventure_game",
    "forks_url": "https://api.github.com/repos/rogersgt/adventure_game/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/adventure_game/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/adventure_game/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/adventure_game/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/adventure_game/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/adventure_game/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/adventure_game/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/adventure_game/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/adventure_game/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/adventure_game/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/adventure_game/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/adventure_game/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/adventure_game/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/adventure_game/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/adventure_game/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/adventure_game/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/adventure_game/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/adventure_game/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/adventure_game/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/adventure_game/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/adventure_game/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/adventure_game/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/adventure_game/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/adventure_game/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/adventure_game/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/adventure_game/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/adventure_game/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/adventure_game/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/adventure_game/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/adventure_game/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/adventure_game/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/adventure_game/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/adventure_game/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/adventure_game/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/adventure_game/releases{/id}",
    "created_at": "2015-10-14T16:59:18Z",
    "updated_at": "2015-10-15T06:53:05Z",
    "pushed_at": "2015-10-15T13:17:44Z",
    "git_url": "git://github.com/rogersgt/adventure_game.git",
    "ssh_url": "git@github.com:rogersgt/adventure_game.git",
    "clone_url": "https://github.com/rogersgt/adventure_game.git",
    "svn_url": "https://github.com/rogersgt/adventure_game",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 43845776,
    "name": "Day2OctoCat",
    "full_name": "rogersgt/Day2OctoCat",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/Day2OctoCat",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/Day2OctoCat",
    "forks_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/Day2OctoCat/releases{/id}",
    "created_at": "2015-10-07T21:29:43Z",
    "updated_at": "2015-10-07T21:38:50Z",
    "pushed_at": "2015-10-07T21:38:50Z",
    "git_url": "git://github.com/rogersgt/Day2OctoCat.git",
    "ssh_url": "git@github.com:rogersgt/Day2OctoCat.git",
    "clone_url": "https://github.com/rogersgt/Day2OctoCat.git",
    "svn_url": "https://github.com/rogersgt/Day2OctoCat",
    "homepage": null,
    "size": 104,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 44646910,
    "name": "Github_recreated_profile",
    "full_name": "rogersgt/Github_recreated_profile",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/Github_recreated_profile",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/Github_recreated_profile",
    "forks_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/Github_recreated_profile/releases{/id}",
    "created_at": "2015-10-21T02:08:51Z",
    "updated_at": "2015-10-21T04:30:52Z",
    "pushed_at": "2015-10-21T04:30:51Z",
    "git_url": "git://github.com/rogersgt/Github_recreated_profile.git",
    "ssh_url": "git@github.com:rogersgt/Github_recreated_profile.git",
    "clone_url": "https://github.com/rogersgt/Github_recreated_profile.git",
    "svn_url": "https://github.com/rogersgt/Github_recreated_profile",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 44334054,
    "name": "LoopsAndIteration",
    "full_name": "rogersgt/LoopsAndIteration",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/LoopsAndIteration",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration",
    "forks_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/releases{/id}",
    "created_at": "2015-10-15T17:30:21Z",
    "updated_at": "2015-10-16T13:16:54Z",
    "pushed_at": "2015-10-16T13:26:46Z",
    "git_url": "git://github.com/rogersgt/LoopsAndIteration.git",
    "ssh_url": "git@github.com:rogersgt/LoopsAndIteration.git",
    "clone_url": "https://github.com/rogersgt/LoopsAndIteration.git",
    "svn_url": "https://github.com/rogersgt/LoopsAndIteration",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 44622816,
    "name": "map-filter",
    "full_name": "rogersgt/map-filter",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/map-filter",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/map-filter",
    "forks_url": "https://api.github.com/repos/rogersgt/map-filter/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/map-filter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/map-filter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/map-filter/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/map-filter/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/map-filter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/map-filter/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/map-filter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/map-filter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/map-filter/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/map-filter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/map-filter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/map-filter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/map-filter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/map-filter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/map-filter/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/map-filter/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/map-filter/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/map-filter/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/map-filter/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/map-filter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/map-filter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/map-filter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/map-filter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/map-filter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/map-filter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/map-filter/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/map-filter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/map-filter/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/map-filter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/map-filter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/map-filter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/map-filter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/map-filter/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/map-filter/releases{/id}",
    "created_at": "2015-10-20T17:23:17Z",
    "updated_at": "2015-10-21T02:03:24Z",
    "pushed_at": "2015-10-21T13:46:30Z",
    "git_url": "git://github.com/rogersgt/map-filter.git",
    "ssh_url": "git@github.com:rogersgt/map-filter.git",
    "clone_url": "https://github.com/rogersgt/map-filter.git",
    "svn_url": "https://github.com/rogersgt/map-filter",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 43963526,
    "name": "peralta",
    "full_name": "rogersgt/peralta",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/peralta",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/peralta",
    "forks_url": "https://api.github.com/repos/rogersgt/peralta/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/peralta/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/peralta/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/peralta/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/peralta/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/peralta/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/peralta/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/peralta/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/peralta/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/peralta/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/peralta/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/peralta/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/peralta/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/peralta/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/peralta/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/peralta/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/peralta/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/peralta/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/peralta/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/peralta/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/peralta/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/peralta/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/peralta/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/peralta/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/peralta/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/peralta/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/peralta/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/peralta/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/peralta/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/peralta/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/peralta/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/peralta/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/peralta/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/peralta/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/peralta/releases{/id}",
    "created_at": "2015-10-09T15:16:46Z",
    "updated_at": "2015-10-13T21:10:54Z",
    "pushed_at": "2015-10-14T03:57:12Z",
    "git_url": "git://github.com/rogersgt/peralta.git",
    "ssh_url": "git@github.com:rogersgt/peralta.git",
    "clone_url": "https://github.com/rogersgt/peralta.git",
    "svn_url": "https://github.com/rogersgt/peralta",
    "homepage": null,
    "size": 5244,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 1,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 43828010,
    "name": "Personal-Bio-Page-Day1",
    "full_name": "rogersgt/Personal-Bio-Page-Day1",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/Personal-Bio-Page-Day1",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1",
    "forks_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1/releases{/id}",
    "created_at": "2015-10-07T16:06:16Z",
    "updated_at": "2015-10-07T16:58:13Z",
    "pushed_at": "2015-10-07T16:58:12Z",
    "git_url": "git://github.com/rogersgt/Personal-Bio-Page-Day1.git",
    "ssh_url": "git@github.com:rogersgt/Personal-Bio-Page-Day1.git",
    "clone_url": "https://github.com/rogersgt/Personal-Bio-Page-Day1.git",
    "svn_url": "https://github.com/rogersgt/Personal-Bio-Page-Day1",
    "homepage": null,
    "size": 108,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 43916443,
    "name": "Surf-Site",
    "full_name": "rogersgt/Surf-Site",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/Surf-Site",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/Surf-Site",
    "forks_url": "https://api.github.com/repos/rogersgt/Surf-Site/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/Surf-Site/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/Surf-Site/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/Surf-Site/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/Surf-Site/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/Surf-Site/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/Surf-Site/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/Surf-Site/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/Surf-Site/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/Surf-Site/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/Surf-Site/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/Surf-Site/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/Surf-Site/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/Surf-Site/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/Surf-Site/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/Surf-Site/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/Surf-Site/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/Surf-Site/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/Surf-Site/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/Surf-Site/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/Surf-Site/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/Surf-Site/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/Surf-Site/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/Surf-Site/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/Surf-Site/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/Surf-Site/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/Surf-Site/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/Surf-Site/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/Surf-Site/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/Surf-Site/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/Surf-Site/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/Surf-Site/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/Surf-Site/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/Surf-Site/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/Surf-Site/releases{/id}",
    "created_at": "2015-10-08T21:09:18Z",
    "updated_at": "2015-10-13T03:09:35Z",
    "pushed_at": "2015-10-13T03:09:34Z",
    "git_url": "git://github.com/rogersgt/Surf-Site.git",
    "ssh_url": "git@github.com:rogersgt/Surf-Site.git",
    "clone_url": "https://github.com/rogersgt/Surf-Site.git",
    "svn_url": "https://github.com/rogersgt/Surf-Site",
    "homepage": null,
    "size": 3612,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 44386892,
    "name": "testing",
    "full_name": "rogersgt/testing",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/testing",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/testing",
    "forks_url": "https://api.github.com/repos/rogersgt/testing/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/testing/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/testing/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/testing/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/testing/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/testing/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/testing/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/testing/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/testing/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/testing/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/testing/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/testing/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/testing/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/testing/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/testing/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/testing/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/testing/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/testing/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/testing/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/testing/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/testing/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/testing/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/testing/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/testing/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/testing/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/testing/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/testing/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/testing/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/testing/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/testing/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/testing/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/testing/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/testing/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/testing/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/testing/releases{/id}",
    "created_at": "2015-10-16T13:28:52Z",
    "updated_at": "2015-10-16T13:28:52Z",
    "pushed_at": "2015-10-16T13:28:52Z",
    "git_url": "git://github.com/rogersgt/testing.git",
    "ssh_url": "git@github.com:rogersgt/testing.git",
    "clone_url": "https://github.com/rogersgt/testing.git",
    "svn_url": "https://github.com/rogersgt/testing",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 44552304,
    "name": "word-count",
    "full_name": "rogersgt/word-count",
    "owner": {
      "login": "rogersgt",
      "id": 14983357,
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "html_url": "https://github.com/rogersgt",
      "followers_url": "https://api.github.com/users/rogersgt/followers",
      "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
      "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
      "organizations_url": "https://api.github.com/users/rogersgt/orgs",
      "repos_url": "https://api.github.com/users/rogersgt/repos",
      "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rogersgt/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/rogersgt/word-count",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/rogersgt/word-count",
    "forks_url": "https://api.github.com/repos/rogersgt/word-count/forks",
    "keys_url": "https://api.github.com/repos/rogersgt/word-count/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/rogersgt/word-count/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/rogersgt/word-count/teams",
    "hooks_url": "https://api.github.com/repos/rogersgt/word-count/hooks",
    "issue_events_url": "https://api.github.com/repos/rogersgt/word-count/issues/events{/number}",
    "events_url": "https://api.github.com/repos/rogersgt/word-count/events",
    "assignees_url": "https://api.github.com/repos/rogersgt/word-count/assignees{/user}",
    "branches_url": "https://api.github.com/repos/rogersgt/word-count/branches{/branch}",
    "tags_url": "https://api.github.com/repos/rogersgt/word-count/tags",
    "blobs_url": "https://api.github.com/repos/rogersgt/word-count/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/rogersgt/word-count/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/rogersgt/word-count/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/rogersgt/word-count/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/rogersgt/word-count/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/rogersgt/word-count/languages",
    "stargazers_url": "https://api.github.com/repos/rogersgt/word-count/stargazers",
    "contributors_url": "https://api.github.com/repos/rogersgt/word-count/contributors",
    "subscribers_url": "https://api.github.com/repos/rogersgt/word-count/subscribers",
    "subscription_url": "https://api.github.com/repos/rogersgt/word-count/subscription",
    "commits_url": "https://api.github.com/repos/rogersgt/word-count/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/rogersgt/word-count/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/rogersgt/word-count/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/rogersgt/word-count/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/rogersgt/word-count/contents/{+path}",
    "compare_url": "https://api.github.com/repos/rogersgt/word-count/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/rogersgt/word-count/merges",
    "archive_url": "https://api.github.com/repos/rogersgt/word-count/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/rogersgt/word-count/downloads",
    "issues_url": "https://api.github.com/repos/rogersgt/word-count/issues{/number}",
    "pulls_url": "https://api.github.com/repos/rogersgt/word-count/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/rogersgt/word-count/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/rogersgt/word-count/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/rogersgt/word-count/labels{/name}",
    "releases_url": "https://api.github.com/repos/rogersgt/word-count/releases{/id}",
    "created_at": "2015-10-19T17:41:59Z",
    "updated_at": "2015-10-19T23:25:09Z",
    "pushed_at": "2015-10-19T23:25:07Z",
    "git_url": "git://github.com/rogersgt/word-count.git",
    "ssh_url": "git@github.com:rogersgt/word-count.git",
    "clone_url": "https://github.com/rogersgt/word-count.git",
    "svn_url": "https://github.com/rogersgt/word-count",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
];

var activity =
[
  {
    "id": "3258948796",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44646910,
      "name": "rogersgt/Github_recreated_profile",
      "url": "https://api.github.com/repos/rogersgt/Github_recreated_profile"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-21T02:08:52Z"
  },
  {
    "id": "3258939748",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44622816,
      "name": "rogersgt/map-filter",
      "url": "https://api.github.com/repos/rogersgt/map-filter"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-21T02:03:22Z"
  },
  {
    "id": "3257329502",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44622816,
      "name": "rogersgt/map-filter",
      "url": "https://api.github.com/repos/rogersgt/map-filter"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-20T17:23:17Z"
  },
  {
    "id": "3257304248",
    "type": "ForkEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43770760,
      "name": "TIY-Charleston-Front-End-Oct2015/assignments",
      "url": "https://api.github.com/repos/TIY-Charleston-Front-End-Oct2015/assignments"
    },
    "payload": {
      "forkee": {
        "id": 44622464,
        "name": "assignments",
        "full_name": "rogersgt/assignments",
        "owner": {
          "login": "rogersgt",
          "id": 14983357,
          "avatar_url": "https://avatars.githubusercontent.com/u/14983357?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rogersgt",
          "html_url": "https://github.com/rogersgt",
          "followers_url": "https://api.github.com/users/rogersgt/followers",
          "following_url": "https://api.github.com/users/rogersgt/following{/other_user}",
          "gists_url": "https://api.github.com/users/rogersgt/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rogersgt/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rogersgt/subscriptions",
          "organizations_url": "https://api.github.com/users/rogersgt/orgs",
          "repos_url": "https://api.github.com/users/rogersgt/repos",
          "events_url": "https://api.github.com/users/rogersgt/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rogersgt/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/rogersgt/assignments",
        "description": "",
        "fork": true,
        "url": "https://api.github.com/repos/rogersgt/assignments",
        "forks_url": "https://api.github.com/repos/rogersgt/assignments/forks",
        "keys_url": "https://api.github.com/repos/rogersgt/assignments/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/rogersgt/assignments/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/rogersgt/assignments/teams",
        "hooks_url": "https://api.github.com/repos/rogersgt/assignments/hooks",
        "issue_events_url": "https://api.github.com/repos/rogersgt/assignments/issues/events{/number}",
        "events_url": "https://api.github.com/repos/rogersgt/assignments/events",
        "assignees_url": "https://api.github.com/repos/rogersgt/assignments/assignees{/user}",
        "branches_url": "https://api.github.com/repos/rogersgt/assignments/branches{/branch}",
        "tags_url": "https://api.github.com/repos/rogersgt/assignments/tags",
        "blobs_url": "https://api.github.com/repos/rogersgt/assignments/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/rogersgt/assignments/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/rogersgt/assignments/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/rogersgt/assignments/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/rogersgt/assignments/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/rogersgt/assignments/languages",
        "stargazers_url": "https://api.github.com/repos/rogersgt/assignments/stargazers",
        "contributors_url": "https://api.github.com/repos/rogersgt/assignments/contributors",
        "subscribers_url": "https://api.github.com/repos/rogersgt/assignments/subscribers",
        "subscription_url": "https://api.github.com/repos/rogersgt/assignments/subscription",
        "commits_url": "https://api.github.com/repos/rogersgt/assignments/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/rogersgt/assignments/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/rogersgt/assignments/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/rogersgt/assignments/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/rogersgt/assignments/contents/{+path}",
        "compare_url": "https://api.github.com/repos/rogersgt/assignments/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/rogersgt/assignments/merges",
        "archive_url": "https://api.github.com/repos/rogersgt/assignments/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/rogersgt/assignments/downloads",
        "issues_url": "https://api.github.com/repos/rogersgt/assignments/issues{/number}",
        "pulls_url": "https://api.github.com/repos/rogersgt/assignments/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/rogersgt/assignments/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/rogersgt/assignments/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/rogersgt/assignments/labels{/name}",
        "releases_url": "https://api.github.com/repos/rogersgt/assignments/releases{/id}",
        "created_at": "2015-10-20T17:16:30Z",
        "updated_at": "2015-10-16T05:06:02Z",
        "pushed_at": "2015-10-20T16:09:08Z",
        "git_url": "git://github.com/rogersgt/assignments.git",
        "ssh_url": "git@github.com:rogersgt/assignments.git",
        "clone_url": "https://github.com/rogersgt/assignments.git",
        "svn_url": "https://github.com/rogersgt/assignments",
        "homepage": null,
        "size": 7612,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "public": true
      }
    },
    "public": true,
    "created_at": "2015-10-20T17:16:30Z",
    "org": {
      "id": 14251473,
      "login": "TIY-Charleston-Front-End-Oct2015",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/TIY-Charleston-Front-End-Oct2015",
      "avatar_url": "https://avatars.githubusercontent.com/u/14251473?"
    }
  },
  {
    "id": "3254332340",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44552304,
      "name": "rogersgt/word-count",
      "url": "https://api.github.com/repos/rogersgt/word-count"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-19T23:25:07Z"
  },
  {
    "id": "3253119885",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44552304,
      "name": "rogersgt/word-count",
      "url": "https://api.github.com/repos/rogersgt/word-count"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-19T17:41:59Z"
  },
  {
    "id": "3245943941",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44386892,
      "name": "rogersgt/testing",
      "url": "https://api.github.com/repos/rogersgt/testing"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-16T13:28:52Z"
  },
  {
    "id": "3245936854",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44334054,
      "name": "rogersgt/LoopsAndIteration",
      "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration"
    },
    "payload": {
      "push_id": 829763736,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "42812700db5b0bf528f890e18473b4c5bb567120",
      "before": "f1d9732d29505ade7bd7c86dbff7571838c9fe82",
      "commits": [
        {
          "sha": "42812700db5b0bf528f890e18473b4c5bb567120",
          "author": {
            "email": "gradyrogers@Gradys-MacBook-Pro.local",
            "name": "Grady Rogers"
          },
          "message": "reworked map",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/commits/42812700db5b0bf528f890e18473b4c5bb567120"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-16T13:26:46Z"
  },
  {
    "id": "3245911844",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44334054,
      "name": "rogersgt/LoopsAndIteration",
      "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration"
    },
    "payload": {
      "push_id": 829754072,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "f1d9732d29505ade7bd7c86dbff7571838c9fe82",
      "before": "1f60afd4d7f47203dcc580a8768bf29709fe41b1",
      "commits": [
        {
          "sha": "f1d9732d29505ade7bd7c86dbff7571838c9fe82",
          "author": {
            "email": "gradyrogers@Gradys-MacBook-Pro.local",
            "name": "Grady Rogers"
          },
          "message": "Completed",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration/commits/f1d9732d29505ade7bd7c86dbff7571838c9fe82"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-16T13:19:14Z"
  },
  {
    "id": "3245904515",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44334054,
      "name": "rogersgt/LoopsAndIteration",
      "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-16T13:16:53Z"
  },
  {
    "id": "3242876549",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44334054,
      "name": "rogersgt/LoopsAndIteration",
      "url": "https://api.github.com/repos/rogersgt/LoopsAndIteration"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-15T17:30:22Z"
  },
  {
    "id": "3241843932",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44262904,
      "name": "rogersgt/adventure_game",
      "url": "https://api.github.com/repos/rogersgt/adventure_game"
    },
    "payload": {
      "push_id": 828269156,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "72605c8258fdcc82bd7b723712d254f20f0af647",
      "before": "a266e4e21d0126503e6c951ff875161d1ccbe0d8",
      "commits": [
        {
          "sha": "72605c8258fdcc82bd7b723712d254f20f0af647",
          "author": {
            "email": "gradyrogers@Gradys-MacBook-Pro.local",
            "name": "Grady Rogers"
          },
          "message": "more styling/minor bug fix",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/adventure_game/commits/72605c8258fdcc82bd7b723712d254f20f0af647"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-15T13:17:44Z"
  },
  {
    "id": "3241658800",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44262904,
      "name": "rogersgt/adventure_game",
      "url": "https://api.github.com/repos/rogersgt/adventure_game"
    },
    "payload": {
      "push_id": 828201173,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "a266e4e21d0126503e6c951ff875161d1ccbe0d8",
      "before": "139ba7f45fc76fea5cec9b734f0fc8e1e464f381",
      "commits": [
        {
          "sha": "a266e4e21d0126503e6c951ff875161d1ccbe0d8",
          "author": {
            "email": "gradyrogers@gradys-mbp.attlocal.net",
            "name": "Grady Rogers"
          },
          "message": "fixed some style",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/adventure_game/commits/a266e4e21d0126503e6c951ff875161d1ccbe0d8"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-15T12:24:08Z"
  },
  {
    "id": "3240740926",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44262904,
      "name": "rogersgt/adventure_game",
      "url": "https://api.github.com/repos/rogersgt/adventure_game"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-15T06:53:05Z"
  },
  {
    "id": "3238627189",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 44262904,
      "name": "rogersgt/adventure_game",
      "url": "https://api.github.com/repos/rogersgt/adventure_game"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-14T16:59:18Z"
  },
  {
    "id": "3236324078",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/peralta",
      "url": "https://api.github.com/repos/rogersgt/peralta"
    },
    "payload": {
      "push_id": 826219349,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "7803439b4563b04647287ab7d2a191cc1369b264",
      "before": "1da120d014fa5184d3bc2bc4edeb9d091c4588f1",
      "commits": [
        {
          "sha": "7803439b4563b04647287ab7d2a191cc1369b264",
          "author": {
            "email": "gradyrogers@gradys-mbp.attlocal.net",
            "name": "Grady Rogers"
          },
          "message": "Most Final",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/peralta/commits/7803439b4563b04647287ab7d2a191cc1369b264"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-14T03:57:13Z"
  },
  {
    "id": "3236262372",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/peralta",
      "url": "https://api.github.com/repos/rogersgt/peralta"
    },
    "payload": {
      "push_id": 826196045,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "1da120d014fa5184d3bc2bc4edeb9d091c4588f1",
      "before": "ebe21af01184dc4710c4e13c8f5be416728fa589",
      "commits": [
        {
          "sha": "1da120d014fa5184d3bc2bc4edeb9d091c4588f1",
          "author": {
            "email": "gradyrogers@gradys-mbp.attlocal.net",
            "name": "Grady Rogers"
          },
          "message": "Final",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/peralta/commits/1da120d014fa5184d3bc2bc4edeb9d091c4588f1"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-14T03:18:56Z"
  },
  {
    "id": "3235390088",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/peralta",
      "url": "https://api.github.com/repos/rogersgt/peralta"
    },
    "payload": {
      "push_id": 825892480,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "ebe21af01184dc4710c4e13c8f5be416728fa589",
      "before": "f4c7d635290e517d6a194713e6ad2989400cb818",
      "commits": [
        {
          "sha": "ebe21af01184dc4710c4e13c8f5be416728fa589",
          "author": {
            "email": "gradyrogers@Gradys-MacBook-Pro.local",
            "name": "Grady Rogers"
          },
          "message": "First Commit Responsive",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/peralta/commits/ebe21af01184dc4710c4e13c8f5be416728fa589"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-13T21:10:54Z"
  },
  {
    "id": "3234313370",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/peralta",
      "url": "https://api.github.com/repos/rogersgt/peralta"
    },
    "payload": {
      "push_id": 825507530,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "f4c7d635290e517d6a194713e6ad2989400cb818",
      "before": "6ea557d0bde054511fa5499fab08259118d3188e",
      "commits": [
        {
          "sha": "f4c7d635290e517d6a194713e6ad2989400cb818",
          "author": {
            "email": "gradyrogers@Gradys-MacBook-Pro.local",
            "name": "Grady Rogers"
          },
          "message": "Safety commit clean code",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/peralta/commits/f4c7d635290e517d6a194713e6ad2989400cb818"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-13T16:23:03Z"
  },
  {
    "id": "3232042864",
    "type": "PushEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43916443,
      "name": "rogersgt/Surf-Site",
      "url": "https://api.github.com/repos/rogersgt/Surf-Site"
    },
    "payload": {
      "push_id": 824647536,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "ec5a92da21188308402562693b3d99a2747de2e3",
      "before": "2b1c8d57bcd54e9f830d3747e131af6a0c24efe8",
      "commits": [
        {
          "sha": "ec5a92da21188308402562693b3d99a2747de2e3",
          "author": {
            "email": "gradyrogers@gradys-mbp.attlocal.net",
            "name": "Grady Rogers"
          },
          "message": "first response commit",
          "distinct": true,
          "url": "https://api.github.com/repos/rogersgt/Surf-Site/commits/ec5a92da21188308402562693b3d99a2747de2e3"
        }
      ]
    },
    "public": true,
    "created_at": "2015-10-13T03:09:35Z"
  },
  {
    "id": "3228449933",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/peralta",
      "url": "https://api.github.com/repos/rogersgt/peralta"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-12T02:17:34Z"
  },
  {
    "id": "3224420311",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43963526,
      "name": "rogersgt/powell-skateboard",
      "url": "https://api.github.com/repos/rogersgt/powell-skateboard"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-09T15:16:47Z"
  },
  {
    "id": "3222780792",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43916443,
      "name": "rogersgt/Surf-Site",
      "url": "https://api.github.com/repos/rogersgt/Surf-Site"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-09T04:40:34Z"
  },
  {
    "id": "3221851376",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43916443,
      "name": "rogersgt/Surf-Site",
      "url": "https://api.github.com/repos/rogersgt/Surf-Site"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-08T21:09:18Z"
  },
  {
    "id": "3217895924",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43845776,
      "name": "rogersgt/Day2OctoCat",
      "url": "https://api.github.com/repos/rogersgt/Day2OctoCat"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-07T21:38:50Z"
  },
  {
    "id": "3217863555",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43845776,
      "name": "rogersgt/Day2OctoCat",
      "url": "https://api.github.com/repos/rogersgt/Day2OctoCat"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-07T21:29:43Z"
  },
  {
    "id": "3216858353",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43828010,
      "name": "rogersgt/Personal-Bio-Page-Day1",
      "url": "https://api.github.com/repos/rogersgt/Personal-Bio-Page-Day1"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-07T16:58:13Z"
  },
  {
    "id": "3216661784",
    "type": "CreateEvent",
    "actor": {
      "id": 14983357,
      "login": "rogersgt",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rogersgt",
      "avatar_url": "https://avatars.githubusercontent.com/u/14983357?"
    },
    "repo": {
      "id": 43828010,
      "name": "rogersgt/Rogers1",
      "url": "https://api.github.com/repos/rogersgt/Rogers1"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-10-07T16:06:16Z"
  }
];

var orgs =
[

];
